---
containerd_package_info:
  enablerepo: "docker-ce"
  pkgs:
    - "{{ containerd_versioned_pkg[containerd_version | string] }}"

containerd_repo_key_info:
  pkg_key: ''
  repo_keys: []

containerd_repo_info:
  pkg_repo: ''
  repos: []
